<?php
/**
 * Registers admin menus, enqueues admin assets, and dispatches form submissions.
 */

namespace BabypasaNewsletter\Admin;

defined( 'ABSPATH' ) || exit;

class Admin {

	public function __construct() {
		add_action( 'admin_menu',            array( $this, 'register_menus' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
	}

	public function register_menus(): void {
		add_menu_page(
			__( 'Newsletter', 'babypasa-newsletter' ),
			__( 'Newsletter', 'babypasa-newsletter' ),
			'manage_options',
			'bpnl-subscribers',
			array( $this, 'render_subscribers' ),
			'dashicons-email-alt',
			25
		);

		add_submenu_page(
			'bpnl-subscribers',
			__( 'Subscribers', 'babypasa-newsletter' ),
			__( 'Subscribers', 'babypasa-newsletter' ),
			'manage_options',
			'bpnl-subscribers',
			array( $this, 'render_subscribers' )
		);

		add_submenu_page(
			'bpnl-subscribers',
			__( 'Email Templates', 'babypasa-newsletter' ),
			__( 'Email Templates', 'babypasa-newsletter' ),
			'manage_options',
			'bpnl-templates',
			array( $this, 'render_templates' )
		);
	}

	public function enqueue_assets( string $hook ): void {
		$allowed_hooks = array(
			'toplevel_page_bpnl-subscribers',
			'newsletter_page_bpnl-templates',
		);
		if ( ! in_array( $hook, $allowed_hooks, true ) ) {
			return;
		}

		wp_enqueue_style(
			'bpnl-admin',
			BPNL_PLUGIN_URL . 'admin/assets/css/bpnl-admin.css',
			array(),
			filemtime( BPNL_PLUGIN_DIR . 'admin/assets/css/bpnl-admin.css' )
		);

		wp_enqueue_script(
			'bpnl-admin',
			BPNL_PLUGIN_URL . 'admin/assets/js/bpnl-admin.js',
			array( 'jquery' ),
			filemtime( BPNL_PLUGIN_DIR . 'admin/assets/js/bpnl-admin.js' ),
			true
		);

		wp_localize_script(
			'bpnl-admin',
			'bpnlAdmin',
			array(
				'ajaxUrl' => admin_url( 'admin-ajax.php' ),
				'nonce'   => wp_create_nonce( 'bpnl_admin_nonce' ),
			)
		);
	}

	public function render_subscribers(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to access this page.', 'babypasa-newsletter' ) );
		}
		$this->handle_bulk_actions();
		require BPNL_PLUGIN_DIR . 'admin/views/subscribers.php';
	}

	public function render_templates(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to access this page.', 'babypasa-newsletter' ) );
		}
		$this->handle_template_reset();
		$this->handle_template_save();
		require BPNL_PLUGIN_DIR . 'admin/views/templates.php';
	}

	private function handle_template_reset(): void {
		if ( empty( $_POST['bpnl_reset_template'] ) || ! isset( $_POST['bpnl_template_nonce'] ) ) {
			return;
		}

		check_admin_referer( 'bpnl_save_template', 'bpnl_template_nonce' );

		$tab = sanitize_text_field( wp_unslash( $_POST['bpnl_reset_template'] ) );

		if ( 'welcome' === $tab ) {
			$tpl = \BabypasaNewsletter\Includes\Email::get_default_welcome_template();
			\BabypasaNewsletter\Includes\Email::save_template( 'bpnl_template_welcome', $tpl );
		}

		add_action( 'admin_notices', function () {
			echo '<div class="notice notice-success is-dismissible"><p>'
				. esc_html__( 'Template restored to default.', 'babypasa-newsletter' )
				. '</p></div>';
		} );
	}

	private function handle_bulk_actions(): void {
		// WP_List_Table sets action / action2 from the bulk dropdown.
		$action = '';
		if ( isset( $_POST['action'] ) && '-1' !== $_POST['action'] ) {
			$action = sanitize_text_field( wp_unslash( $_POST['action'] ) );
		} elseif ( isset( $_POST['action2'] ) && '-1' !== $_POST['action2'] ) {
			$action = sanitize_text_field( wp_unslash( $_POST['action2'] ) );
		}

		if ( empty( $action ) ) {
			return;
		}

		// The nonce generated by WP_List_Table uses 'bulk-' + plural arg ('subscribers').
		check_admin_referer( 'bulk-subscribers' );

		$ids = isset( $_POST['subscriber_ids'] )
			? array_map( 'intval', (array) $_POST['subscriber_ids'] )
			: array();

		if ( 'delete' === $action && ! empty( $ids ) ) {
			\BabypasaNewsletter\Includes\Subscriber::delete_by_ids( $ids );
			add_action( 'admin_notices', function () {
				echo '<div class="notice notice-success is-dismissible"><p>'
					. esc_html__( 'Selected subscribers deleted.', 'babypasa-newsletter' )
					. '</p></div>';
			} );
		}
	}

	private function handle_template_save(): void {
		if ( ! isset( $_POST['bpnl_template_nonce'] ) ) {
			return;
		}

		check_admin_referer( 'bpnl_save_template', 'bpnl_template_nonce' );

		$tab = isset( $_POST['bpnl_tab'] ) ? sanitize_text_field( wp_unslash( $_POST['bpnl_tab'] ) ) : 'welcome';
		$key = ( 'newsletter' === $tab ) ? 'bpnl_template_newsletter' : 'bpnl_template_welcome';

		\BabypasaNewsletter\Includes\Email::save_template(
			$key,
			array(
				'subject'  => sanitize_text_field( wp_unslash( $_POST['bpnl_subject'] ?? '' ) ),
				'body'     => wp_unslash( $_POST['bpnl_body'] ?? '' ), // manage_options only; full HTML needed for email templates.
				'reply_to' => sanitize_email( wp_unslash( $_POST['bpnl_reply_to'] ?? '' ) ),
			)
		);

		add_action( 'admin_notices', function () {
			echo '<div class="notice notice-success is-dismissible"><p>'
				. esc_html__( 'Template saved successfully.', 'babypasa-newsletter' )
				. '</p></div>';
		} );
	}
}
